name: Ejercicio 1

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir nombre
        run: echo Hola, mi nombre es Andres Lopez Alfaro

      - name: Imprimir fecha y hora actual
        run: date

      - name: Imprimir sistema operativo
        run: echo $RUNNER_OS
